version: '3.9'
services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
       ALLOW_ANONYMOUS_LOGIN : yes
       ALLOW_PLAINTEXT_LISTENER : yes
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
       KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
       KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://127.0.0.1:9092'
       ALLOW_ANONYMOUS_LOGIN : yes
       ALLOW_PLAINTEXT_LISTENER : yes
